// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_1xImNFIqEbONQBce12DIv2lBH1_vw-Q',
    appId: '1:1031182155270:web:2ac3a4c22e96a9b1260d87',
    messagingSenderId: '1031182155270',
    projectId: 'dl-flutter',
    authDomain: 'dl-flutter.firebaseapp.com',
    storageBucket: 'dl-flutter.appspot.com',
    measurementId: 'G-8WZ7WRP052',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoycwKbN_Ne33puXeso5ZZD3-SHfJjR-o',
    appId: '1:1031182155270:android:061d55a94c65ef97260d87',
    messagingSenderId: '1031182155270',
    projectId: 'dl-flutter',
    storageBucket: 'dl-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxgvI2UqWRxHNoRJ-JaO5O5Qamfc-FFI',
    appId: '1:1031182155270:ios:8ad2ccfcea7967f3260d87',
    messagingSenderId: '1031182155270',
    projectId: 'dl-flutter',
    storageBucket: 'dl-flutter.appspot.com',
    iosClientId: '1031182155270-95nnlu4j999cb11bb005seunnhr15ddi.apps.googleusercontent.com',
    iosBundleId: 'com.example.dlFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoxgvI2UqWRxHNoRJ-JaO5O5Qamfc-FFI',
    appId: '1:1031182155270:ios:8ad2ccfcea7967f3260d87',
    messagingSenderId: '1031182155270',
    projectId: 'dl-flutter',
    storageBucket: 'dl-flutter.appspot.com',
    iosClientId: '1031182155270-95nnlu4j999cb11bb005seunnhr15ddi.apps.googleusercontent.com',
    iosBundleId: 'com.example.dlFlutterApp',
  );
}
